In [26]:
import pandas as pd
import numpy as np
import os
from scipy.stats import chi2_contingency

In [8]:
table=pd.read_excel("HEART.xlsx")

In [9]:
table.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [10]:
#Age: Age of experimental unit
#Sex: 1 for male, 0 for female
#Cp: Chest pain : 1: typical type 1 angina , 2: typical type angina, 3: non-angina pain , 4: asymptomatic
#trestbps: trest blood pressure 
#chol : Serum cholestrol
#fbs: Fasting blood suagr : 1: >120 , 0: <120
#restecg : 0:Normal , 1: St-T wave abnormal , 2: probable or define left ventricular hypertrophy
#thalach: maximum HB received
#exang: exercise induced angina , 1: yes, 0: no
#oldpeak: ST depression
#Slope: slope of peak exercise, 1:upwardsloping, 2:flat,3:downward sloping
#CA: number of major vessels colored
#Thal: 1:normal,2:fixed defect , 3: reversible defect
#Terget: individual suffer from cardiovascular disease or not , 1: yes , 0: no

In [12]:
table["sex"] = table.sex.astype("category")
table["cp"] = table.cp.astype("category")
table["fbs"] = table.fbs.astype("category")
table["exang"] = table.exang.astype("category")
table["slope"] = table.slope.astype("category")
table["ca"] = table.ca.astype("category")
table["thal"] = table.thal.astype("category")
table["target"] = table.target.astype("category")

In [56]:
table.dtypes

age            int64
sex         category
cp          category
trestbps       int64
chol           int64
fbs         category
restecg        int64
thalach        int64
exang       category
oldpeak      float64
slope       category
ca          category
thal        category
target      category
dtype: object

In [39]:
df1= pd.crosstab(df['sex'], df['target']) 
print(df1) 
c, p, dof, expected = chi2_contingency(df1) 
c,p,dof,expected

target    0   1
sex            
0        24  72
1       114  93


(22.717227046576355,
 1.8767776216941503e-06,
 1,
 array([[ 43.72277228,  52.27722772],
        [ 94.27722772, 112.72277228]]))

In [38]:
df2= pd.crosstab(df['cp'], df['target']) 
print(df2) 
c, p, dof, expected = chi2_contingency(df2) 
c,p,dof,expected

target    0   1
cp             
0       104  39
1         9  41
2        18  69
3         7  16


(81.68642755194445,
 1.3343043373050064e-17,
 3,
 array([[65.12871287, 77.87128713],
        [22.77227723, 27.22772277],
        [39.62376238, 47.37623762],
        [10.47524752, 12.52475248]]))

In [37]:
df3= pd.crosstab(df['fbs'], df['target']) 
print(df3) 
c, p, dof, expected = chi2_contingency(df3) 
c,p,dof,expected

target    0    1
fbs             
0       116  142
1        22   23


(0.10627276301947715, 0.7444281114149577, 1, array([[117.5049505, 140.4950495],
        [ 20.4950495,  24.5049505]]))

In [41]:
df4= pd.crosstab(df['restecg'], df['target']) 
print(df4) 
c, p, dof, expected = chi2_contingency(df4) 
c,p,dof,expected

target    0   1
restecg        
0        79  68
1        56  96
2         3   1


(10.023091785081, 0.006660598773498031, 2, array([[66.95049505, 80.04950495],
        [69.22772277, 82.77227723],
        [ 1.82178218,  2.17821782]]))

In [42]:
df5= pd.crosstab(df['exang'], df['target']) 
print(df5) 
c, p, dof, expected = chi2_contingency(df5) 
c,p,dof,expected

target   0    1
exang          
0       62  142
1       76   23


(55.94454996665093,
 7.454409331235655e-14,
 1,
 array([[ 92.91089109, 111.08910891],
        [ 45.08910891,  53.91089109]]))

In [44]:
df6= pd.crosstab(df['slope'], df['target']) 
print(df6) 
c, p, dof, expected = chi2_contingency(df6) 
c,p,dof,expected

target   0    1
slope          
0       12    9
1       91   49
2       35  107


(47.506896756030244,
 4.830681934276837e-11,
 2,
 array([[ 9.56435644, 11.43564356],
        [63.76237624, 76.23762376],
        [64.67326733, 77.32673267]]))

In [46]:
df8= pd.crosstab(df['ca'], df['target']) 
print(df8) 
c, p, dof, expected = chi2_contingency(df8) 
c,p,dof,expected

target   0    1
ca             
0       46  134
1       44   21
2       31    7
3       17    3


(74.30263036099419,
 5.111663429976987e-16,
 3,
 array([[81.98019802, 98.01980198],
        [29.6039604 , 35.3960396 ],
        [17.30693069, 20.69306931],
        [ 9.10891089, 10.89108911]]))

In [47]:
df7= pd.crosstab(df['thal'], df['target']) 
print(df7) 
c, p, dof, expected = chi2_contingency(df7) 
c,p,dof,expected

target   0    1
thal           
1       12    6
2       37  131
3       89   28


(84.66499002205522,
 4.1231678183157673e-19,
 2,
 array([[ 8.1980198 ,  9.8019802 ],
        [76.51485149, 91.48514851],
        [53.28712871, 63.71287129]]))